### ISSUE TITLE
error with basic Firestore example

### ISSUE THREAD

**Issue by redpandatronicsuk** [wobsoriano/solid-firebase#4]
I get this error:

```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

```tsx
//index.tsx

/* @refresh reload */
import { render } from 'solid-js/web';

import { FirebaseProvider } from 'solid-firebase';
import type { FirebaseOptions } from 'firebase/app';

import './index.css';
import App from './App';

const firebaseConfig: FirebaseOptions = {
  apiKey: 'xxx',
  authDomain: 'xxx,
  databaseURL: 'xxx',
  projectId: 'xxx',
  storageBucket: 'xxx',
  messagingSenderId: 'xxx',
  appId: 'xxx',
};

render(
  () => (
    <FirebaseProvider config={firebaseConfig}>
      <App />
    </FirebaseProvider>
  ),
  document.getElementById('root') as HTMLElement
);

```

```tsx
//App.tsx

import { Component, Match, Switch } from 'solid-js';
import { useFirestore } from 'solid-firebase';
import { collection, getFirestore } from 'firebase/firestore';

const App: Component = () => {
  const db = getFirestore();
  const test = useFirestore(collection(db, 'test'));

  return (
      <Switch>
        <Match when={test.loading}>
          <p>Loading...</p>
        </Match>
        <Match when={test.error}>
          <p>An error occurred.</p>
        </Match>
        <Match when={test.data}>{JSON.stringify(test)}</Match>
      </Switch>
  );
};

export default App;
```

**Comment by wobsoriano** [comment]
Should be fixed https://github.com/wobsoriano/solid-firebase/commit/00aff27d040506f204a5cbf7fac711759988dbb7

**Comment by danielo515** [comment]
I still get this error on a fresh new install. What is the way to fix it? I use Yarn by the way

**Comment by noga-dev** [comment]
@wobsoriano  I'm getting this as well with a fresh install using npm and Astro.

```
D:\Source\challenges\jg\hack\public\main\node_modules\@firebase\app\dist\index.cjs.js:528
        throw ERROR_FACTORY.create("no-app" /* NO_APP */, { appName: name });
                            ^

FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at Object.getApp (D:\Source\challenges\jg\hack\public\main\node_modules\@firebase\app\dist\index.cjs.js:528:29)
    at Proxy.getFirestore (D:\Source\challenges\jg\hack\public\main\node_modules\@firebase\firestore\dist\index.node.cjs.js:26130:35)
    at Media (/src/components/Media.tsx:33:36)
    at Proxy.createComponent (D:\Source\challenges\jg\hack\public\main\node_modules\solid-js\dist\server.cjs:252:15)
    at eval (@astrojs/solid-js/server.js:27:80)
    at Proxy.renderToString (D:\Source\challenges\jg\hack\public\main\node_modules\solid-js\web\dist\server.cjs:250:86)
    at renderToStaticMarkup (@astrojs/solid-js/server.js:27:37)
    at Object.check (@astrojs/solid-js/server.js:10:19)
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/index.js:183:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'app/no-app',
  customData: { appName: '[DEFAULT]' }
```
